### ISSUE TITLE
withConnection triggers additional (undesired) registrations

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/lsp-client#41]
Through a string of calls through `connect`, `initializeConnection`, and registering capabilities, `withConnection` ends up registering hover/def/ref providers on top of what was already registered.

This combined with the fact that the Sourcegraph app calls all of the providers whenever the set changes caused an infinite loop in the Go extension while I was integrating lsp-client.

I see a couple ways to solve this:

- Do not call all providers when the set changes (it may be high time to take another stab at https://github.com/sourcegraph/sourcegraph/issues/2962#issuecomment-478389985)
- Skip registering providers when the connection is initiated by `withConnection`

**Comment by felixfbecker** [comment]
This is expected because the connection can get put into the connection cache and reused by connections that simultaneously get initialized.

Could you explain how the infinite loop happened?

**Comment by chrismwendt** [comment]
In the Go extension, I'm using `withConnection` to query dependent repositories for `workspace/xreferences` (for cross-repository references). That `withConnection` is called inside of a `provideReferences` callback for the external references provider. Here's the relevant line: https://github.com/sourcegraph/sourcegraph-go/pull/36/files#diff-dd20fa40ada2e95ac057919fe5bdcfccR836

Any other ideas how to avoid this? Maybe lsp-client could keep track of which connections have providers registered for them, and `withConnection` would not register providers but connections made from `register` would?

**Comment by felixfbecker** [comment]
But then how does that provider get called again? I.e. where does the loop close?

**Comment by chrismwendt** [comment]
In the Sourcegraph app, all providers get called again whenever the set of providers changes. I don't know the exact call stack, but this is part of it: https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/shared/src/api/client/services/location.ts#L115-145

**Comment by chrismwendt** [comment]
@lguychard had an idea that I'll try to articulate here: do not register providers from `withConnection`, but register providers when a workspace root has been added (by listening to `sourcegraph.workspace.rootChanges`), and refcount the connections. A reference can be 1) a `withConnection` callback, or 2) a provider.

A solution to this will unblock https://github.com/sourcegraph/sourcegraph-go/pull/36

**Comment by chrismwendt** [comment]
I have to switch to other tasks until an appropriate solution to this has been found.
